=====================================
Menu: 
  AND term term ...                  
  OR term term ...                   
  DIFF term not-present-term not-present-term ... 
  PRINT page                         
  INCOMING page                      
  OUTGOING page                      
  QUIT                               
=====================================

$: INCOMING nonexistent.txt

Error

$: OUTGOING nonexistent.txt

Error

$: AND t

2
test-small/dummy.html
test-small/mdParserTest3.md

